### ISSUE TITLE
An issue with manage.py:  ...ModuleNotFoundError: No module named 'askbot_app'

### ISSUE THREAD

**Issue by piggybit** [martin-bts/askbot-devel#109]
I have issue with manage.py, here is the error:
#python3 manage.py collectstatic
Traceback (most recent call last):
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 204, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 211, in fetch_command
    settings.INSTALLED_APPS
  File "/home/thang/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/thang/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/thang/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'askbot_app'

**Comment by piggybit** [comment]
I even cannot askbot-setup:
-----------
...
Copying files:
* __init__.py
* manage.py
* urls.py
* django.wsgi
Creating settings file
Traceback (most recent call last):
  File "/home/thang/.local/bin/askbot-setup", line 11, in <module>
    load_entry_point('askbot', 'console_scripts', 'askbot-setup')()
  File "/usr/local/lib/python3.6/dist-packages/askbot-0.10.2-py3.6.egg/askbot/deployment/__init__.py", line 135, in askbot_setup
    deploy_askbot(options_dict)
  File "/usr/local/lib/python3.6/dist-packages/askbot-0.10.2-py3.6.egg/askbot/deployment/__init__.py", line 195, in deploy_askbot
    context=options
  File "/usr/local/lib/python3.6/dist-packages/askbot-0.10.2-py3.6.egg/askbot/deployment/path_utils.py", line 193, in deploy_into
    settings_contents = SettingsTemplate(context).render()
  File "/home/thang/.local/lib/python3.6/site-packages/pystache-0.3.1-py3.6.egg/pystache/view.py", line 109, in render
  File "/home/thang/.local/lib/python3.6/site-packages/pystache-0.3.1-py3.6.egg/pystache/view.py", line 62, in load_template
NameError: name '**basestring**' is not defined

**Comment by sebastian-philipp** [comment]
Seems to be an error with your dependencies. Try running in a virtual environment.

**Comment by sebastian-philipp** [comment]
and in any case, this repo is outdated. please use the 0.11.x branch in **ASKBOT/askbot-devel**

**Comment by piggybit** [comment]
thanks.
I can askbot-setup by changing "basestring" to "str" in vew.py
then change: 
from:  export DJANGO_SETTINGS_MODULE=**askbot_app**.settings
to right django project name.

However, when i load the web, it's showing default Django page instead of askbot page.
