### ISSUE TITLE
openid: TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#14]
```
py3.6 runtests: commands[0] | coverage run manage.py test askbot.tests.test_permission_assertions
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/models/__init__.py", line 2, in <module>
    startup_procedures.run()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/startup_procedures.py", line 1103, in run
    run_startup_tests()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/startup_procedures.py", line 1029, in run_startup_tests
    test_modules()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/startup_procedures.py", line 309, in test_modules
    try_import(mod_name, pip_path)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/startup_procedures.py", line 210, in try_import
    load_module(module_name)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/utils/loading.py", line 27, in load_module
    return __import__(mod_path, globals(), locals(), [], ABSOLUTE_AND_RELATIVE)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/openid/__init__.py", line 52, in <module>
    if len(version_info) != 3:
TypeError: object of type 'map' has no len()

```

**Comment by sebastian-philipp** [comment]
drop-in replacement python-openid2
