### ISSUE TITLE
Load livesettings templatetags

### ISSUE THREAD

**Issue by martin-bts** [martin-bts/askbot-devel#27]
since `{% load %}` has only been a noop as of late, `{% load config_tags %}` didn't do anything. On the other hand, I am fairly certain that we never load `askbot.deps.livesettings.templatetags.config_tags` anywhere else. So this is missing now.

**Comment by sebastian-philipp** [comment]
Another problem with livesettings: Since django 1.8, modifying django_settings at runtime is [not supported](https://docs.djangoproject.com/en/2.2/topics/settings/#altering-settings-at-runtime). This might be the cause for 

```
======================================================================
ERROR: test_get_invited_moderators2 (askbot.tests.test_user_model.UserModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/tests/utils.py", line 37, in wrapped
    return func(*args, **kwargs)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/tests/test_user_model.py", line 34, in test_get_invited_moderators2
    u = self.create_user('One User', 'one@example.com')
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/tests/utils.py", line 162, in create_user
    reputation=reputation
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/tests/utils.py", line 77, in create_user
    user = models.User.objects.create_user(username, email)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/contrib/auth/models.py", line 159, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/contrib/auth/models.py", line 153, in _create_user
    user.save(using=self._db)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/models/__init__.py", line 4158, in init_avatar_urls
    instance.init_avatar_urls()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/models/__init__.py", line 339, in user_init_avatar_urls
    self.avatar_urls[size] = self.calculate_avatar_url(size)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/models/__init__.py", line 300, in user_calculate_avatar_url
    return self.get_default_avatar_url(size)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/models/__init__.py", line 218, in user_get_default_avatar_url
    return skin_utils.get_media_url(askbot_settings.DEFAULT_AVATAR_URL)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/skins/utils.py", line 156, in get_media_url
    use_skin = resolve_skin_for_media(media=url, preferred_skin = use_skin)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/skins/utils.py", line 88, in resolve_skin_for_media
    available_skins = list(get_available_skins(selected=preferred_skin).items())
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/skins/utils.py", line 46, in get_available_skins
    skins.update(get_skins_from_dir(extra_skins_dir))
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/skins/utils.py", line 26, in get_skins_from_dir
    for item in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpfsighqep'
```

could be solvable with livesettings.

We're altering `django_settings.ASKBOT_EXTRA_SKINS_DIR`  at askbot.tests.test_skins.SkinTests#tearDown

**Comment by sebastian-philipp** [comment]
TIL: `@django.settings.utils.override_settings(ROOT_URLCONF='livesettings.test_urls')`

**Comment by martin-bts** [comment]
django_jinja does this for us atm
