### ISSUE TITLE
lamson library needs to be updated

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#31]
```
ImportError: Failed to import test module: askbot.tests.test_reply_by_email
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/tests/test_reply_by_email.py", line 3, in <module>
    from askbot.mail.lamson_handlers import PROCESS, VALIDATE_EMAIL, get_parts
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/askbot/mail/lamson_handlers.py", line 19, in <module>
    from lamson.server import Relay
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/lamson/server.py", line 184
    except SMTPError, err:
                    ^
SyntaxError: invalid syntax

```

**Comment by rabueker** [comment]
https://github.com/zedshaw/lamson: 

Lamson is written entirely in Python and runs on Python 2.5 or 2.6 but not 3k yet

**Comment by sebastian-philipp** [comment]
yes, that's why we see the syntax erro. is there a fork that supports py3?

**Comment by rabueker** [comment]
lamson is called by django-lamson (https://github.com/vvangelovski/django-lamson/blob/master/django_lamson/management/commands/lamson_start.py)

python3:  https://github.com/dcollinsn/lamson
