### ISSUE TITLE
download user data fails

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#89]
Three distinct Tracebacks for this one:
```
[27/Jun/2019 12:20:51] "GET /s/users/1/download-data/27-06-2019-admin-askbot.zip/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/home/sebastian/Repos/askbot-devel/askbot/utils/file_utils.py", line 21, in read_file_chunkwise
    data = file_obj.read(chunk_size)
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 10: invalid start byte
[27/Jun/2019 12:20:51] "GET /s/users/1/download-data/27-06-2019-admin-askbot.zip/ HTTP/1.1" 500 59
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable
```

```Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/sebastian/Repos/askbot-devel/.tox/py3.6/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by sebastian-philipp** [comment]
first one is fixed by #90
